import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { motion } from 'framer-motion';
import { Search, FileDown, Receipt } from 'lucide-react';
import { billAPI } from '../../api/bill.api';
import LoadingSpinner from '../../components/common/LoadingSpinner';
import { formatINR } from '../../utils/currency.utils';
import { formatDate } from '../../utils/date.utils';

const MyBills = () => {
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);

  const { data, isLoading } = useQuery({ queryKey: ['bills', { search, page }], queryFn: () => billAPI.getAll({ search, page, limit: 20 }).then((r) => r.data.data) });

  const bills = data?.bills || [];
  const pagination = data?.pagination || {};

  const downloadPDF = async (id, num) => {
    try { const { data: blob } = await billAPI.getPDF(id); const url = window.URL.createObjectURL(new Blob([blob])); const a = document.createElement('a'); a.href = url; a.download = `${num}.pdf`; a.click(); window.URL.revokeObjectURL(url); } catch { /* handled */ }
  };

  const getStatusBadge = (status) => {
    const statusMap = {
      paid: { bg: 'bg-success-bg', text: 'text-success-text', border: 'border-[#4CAF50]' },
      pending: { bg: 'bg-warning-bg', text: 'text-warning-text', border: 'border-[#D4A017]' },
      partial: { bg: 'bg-info-bg', text: 'text-info-text', border: 'border-[#3B82F6]' },
      cancelled: { bg: 'bg-danger-bg', text: 'text-danger-text', border: 'border-[#E53935]' }
    };
    const s = statusMap[status] || statusMap.pending;
    return (
      <span className={`inline-flex items-center gap-[5px] px-[10px] py-[3px] rounded-full text-[11px] font-medium tracking-[0.04em] ${s.bg} ${s.text} border border-[rgba(123,28,28,0.08)] uppercase`}>
        {status}
      </span>
    );
  };

  return (
    <div className="space-y-6 max-w-4xl mx-auto font-body">
      <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4">
        <div>
          <h1 className="font-display text-3xl font-bold text-maroon-800 tracking-tight">My Bills</h1>
          <p className="text-sm text-[#9A7A7A] mt-1">{pagination.total || 0} bills generated by you</p>
        </div>
      </div>
      
      <div className="relative w-full max-w-md">
        <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-[18px] h-[18px] text-[#9A7A7A]" />
        <input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search bill number or customer..." className="form-input pl-10" />
      </div>

      {isLoading ? <LoadingSpinner /> : (
        <div className="space-y-4">
          {bills.map((bill, i) => (
            <motion.div key={bill._id} initial={{ y: 10, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: i * 0.02 }}
              className="bg-surface-card border border-[rgba(123,28,28,0.08)] rounded-xl p-4 sm:p-5 flex flex-col sm:flex-row sm:items-center gap-4 hover:shadow-bpc-lg hover:-translate-y-0.5 transition-all duration-300">
              
              <div className="flex items-center gap-4 flex-1 min-w-0">
                <div className="w-12 h-12 rounded-xl bg-maroon-50 border border-maroon-100 flex items-center justify-center text-maroon-700 font-mono font-bold text-[15px] flex-shrink-0">
                  {bill.billNumber?.slice(-3)}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex flex-wrap items-center gap-2.5 mb-1">
                    <p className="font-mono font-semibold text-[#1A0505] text-[15px]">{bill.billNumber}</p>
                    {getStatusBadge(bill.paymentStatus)}
                  </div>
                  <p className="text-[13px] text-[#9A7A7A] truncate flex items-center gap-1.5">
                    <span className="font-medium text-[#5A3A3A]">{bill.customer?.name || 'Walk-in'}</span>
                    <span className="w-1 h-1 rounded-full bg-[#9A7A7A]/40" />
                    {formatDate(bill.billDate)}
                  </p>
                </div>
              </div>
              
              <div className="flex items-center justify-between sm:justify-end gap-5 pl-16 sm:pl-0 border-t border-[rgba(123,28,28,0.05)] sm:border-0 pt-3 sm:pt-0">
                <div className="text-left sm:text-right flex-shrink-0">
                  <p className="font-display font-bold text-maroon-800 text-[18px]">{formatINR(bill.totalAmount)}</p>
                  <p className="text-[11px] font-medium text-[#9A7A7A] tracking-wider uppercase mt-0.5">{bill.billType?.replace('_', ' ')}</p>
                </div>
                <button onClick={() => downloadPDF(bill._id, bill.billNumber)} className="p-2.5 text-[#9A7A7A] hover:text-maroon-600 hover:bg-maroon-50 border border-transparent hover:border-maroon-100 rounded-lg transition-colors flex-shrink-0">
                  <FileDown className="w-5 h-5" />
                </button>
              </div>
            </motion.div>
          ))}
          {bills.length === 0 && (
            <div className="text-center py-20 bg-surface-card rounded-xl border border-[rgba(123,28,28,0.08)]">
              <Receipt className="w-12 h-12 text-maroon-200 mx-auto mb-4" />
              <p className="text-[#5A3A3A] font-medium text-[16px]">No bills found</p>
              <p className="text-[#9A7A7A] text-[14px] mt-1">You haven't generated any bills yet or none match your search.</p>
            </div>
          )}
        </div>
      )}

      {pagination.pages > 1 && (
        <div className="flex items-center justify-center gap-3 pt-4">
          <button onClick={() => setPage((p) => Math.max(1, p - 1))} disabled={page === 1} className="px-4 py-2 text-[13px] font-medium text-[#1A0505] bg-surface-card border border-[rgba(123,28,28,0.15)] rounded-lg hover:bg-maroon-50 transition-colors disabled:opacity-50 disabled:hover:bg-surface-card">Previous</button>
          <span className="text-[13px] font-medium text-[#5A3A3A]">Page <span className="font-bold text-[#1A0505]">{pagination.page}</span> of {pagination.pages}</span>
          <button onClick={() => setPage((p) => Math.min(pagination.pages, p + 1))} disabled={page >= pagination.pages} className="px-4 py-2 text-[13px] font-medium text-[#1A0505] bg-surface-card border border-[rgba(123,28,28,0.15)] rounded-lg hover:bg-maroon-50 transition-colors disabled:opacity-50 disabled:hover:bg-surface-card">Next</button>
        </div>
      )}
    </div>
  );
};

export default MyBills;
